# Generated by Django 4.0.2 on 2022-02-19 13:35

from django.db import migrations, models
import django.db.models.deletion
import folio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(db_index=True, max_length=100, verbose_name='Имя категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CatSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_name', models.CharField(db_index=True, max_length=255, verbose_name='Категория навыков')),
                ('cs_sorting', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Категория навыков',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_organization', models.CharField(max_length=350, verbose_name='Организация')),
                ('p_name', models.CharField(max_length=255, verbose_name='Имя проекта')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('p_description', models.TextField(verbose_name='Описание')),
                ('p_i_did', models.CharField(blank=True, max_length=255, null=True, verbose_name='сфера деятельности')),
                ('p_img', models.ImageField( verbose_name='Фото')),
                ('p_img_preview_png', models.JSONField(blank=True, null=True)),
                ('p_img_preview_webp', models.JSONField(blank=True, null=True)),
                ('p_img_large_png', models.JSONField(blank=True, null=True)),
                ('p_img_large_webp', models.JSONField(blank=True, null=True)),
                ('p_link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('p_git', models.CharField(max_length=255, verbose_name='Github')),
                ('p_sorting', models.IntegerField(verbose_name='Сортировка')),
                ('p_status', models.IntegerField(verbose_name='Статус')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folio.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Проект',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('b_post', models.CharField(max_length=250, verbose_name='Пост')),
                ('b_link', models.CharField(blank=True, max_length=250, verbose_name='Ссылка на Github')),
            ],
            options={
                'verbose_name': 'Бэкенд',
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(db_index=True, max_length=150, verbose_name='Имя вида')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Вид',
            },
        ),
        migrations.CreateModel(
            name='TeamList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folio.project', verbose_name='Проект')),
                ('id_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folio.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Команда',
                'unique_together': {('id_project', 'id_team')},
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(db_index=True, max_length=250, verbose_name='Навыки')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('s_description', models.CharField(max_length=255, verbose_name='Описание')),
                ('s_img', models.ImageField(blank=True, null=True, upload_to='photos/skill_photo/%y/%m/%d', verbose_name='фото')),
                ('s_quantity', models.IntegerField(verbose_name='Количество')),
                ('s_level', models.IntegerField(verbose_name='Уровень')),
                ('s_sorting', models.IntegerField(verbose_name='Сортировка')),
                ('s_status', models.BooleanField(default=True, verbose_name='Статус')),
                ('id_catSkil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folio.catskill', verbose_name='Категория навыка')),
            ],
            options={
                'verbose_name': 'Навыки',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='id_teamlist',
            field=models.ManyToManyField(through='folio.TeamList', to='folio.Team'),
        ),
        migrations.AddField(
            model_name='project',
            name='id_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folio.view', verbose_name='Вид'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='project', to='folio.Skills'),
        ),
    ]
