# Generated by Django 4.0.2 on 2022-02-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Программисты'},
        ),
        migrations.AlterModelOptions(
            name='teamlist',
            options={'verbose_name': 'Список команды'},
        ),
        migrations.AlterField(
            model_name='project',
            name='p_git',
            field=models.CharField(default=None, max_length=255, verbose_name='Github'),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_organization',
            field=models.CharField(default=None, max_length=350, verbose_name='Организация'),
        ),
    ]
