# Generated by Django 4.0.2 on 2022-02-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_alter_team_options_alter_teamlist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id_teamlist',
        ),
        migrations.AddField(
            model_name='project',
            name='id_teamlist',
            field=models.ManyToManyField(blank=True, related_name='project', to='folio.Team'),
        ),
        migrations.DeleteModel(
            name='TeamList',
        ),
    ]
