# Generated by Django 4.0.2 on 2022-02-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0003_alter_project_id_teamlist_delete_teamlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id_teamlist',
            field=models.ManyToManyField(blank=True, related_name='projects', to='folio.Team'),
        ),
    ]
