# Generated by Django 4.0.2 on 2022-03-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0004_alter_project_id_teamlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='id_catSkil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='folio.catskill', verbose_name='Категория навыка'),
        ),
    ]
