# Generated by Django 4.0.2 on 2022-03-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0005_alter_skills_id_catskil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='p_sorting',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
