# Generated by Django 4.0.2 on 2022-03-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0006_alter_project_p_sorting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='p_status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
