# Generated by Django 4.0.2 on 2022-03-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0008_alter_catskill_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='s_img',
            field=models.ImageField(default='photo', upload_to='skills', verbose_name='фото'),
            preserve_default=False,
        ),
    ]
