# Generated by Django 4.0.2 on 2022-03-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0009_alter_skills_s_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
