# Generated by Django 4.0.2 on 2022-03-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0010_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='view',
            name='slug',
        ),
        migrations.AlterField(
            model_name='catskill',
            name='cs_sorting',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id_teamlist',
            field=models.ManyToManyField(blank=True, related_name='projects', to='folio.Team', verbose_name='Принимали участие'),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_description',
            field=models.TextField(verbose_name='Кратко о проекте'),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_git',
            field=models.CharField(default=None, max_length=255, verbose_name='Ссылка на репозиторий'),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_i_did',
            field=models.TextField(default='qwe', verbose_name='Что было сделано мной'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='p_img',
            field=models.ImageField(upload_to='', verbose_name='Фото png 920x600'),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_link',
            field=models.CharField(max_length=255, verbose_name='Ссылка на проект'),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_status',
            field=models.BooleanField(default=True, verbose_name='Показать'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='project', to='folio.Skills', verbose_name='Использовал технологии'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='s_img',
            field=models.ImageField(upload_to='skills', verbose_name='Иконка svg 123x123px'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='s_level',
            field=models.IntegerField(verbose_name='Уровень владения'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='s_name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='s_quantity',
            field=models.IntegerField(verbose_name='Использовал в проектах'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='s_status',
            field=models.BooleanField(default=True, verbose_name='Показать'),
        ),
        migrations.AlterField(
            model_name='team',
            name='b_post',
            field=models.CharField(max_length=250, verbose_name='Специальность'),
        ),
    ]
