# Generated by Django 4.0.2 on 2022-03-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0011_remove_project_slug_remove_skills_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='p_git',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Ссылка на репозиторий'),
        ),
    ]
