# Generated by Django 4.0.2 on 2022-03-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0012_alter_project_p_git'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='p_organization',
            field=models.CharField(blank=True, default=None, max_length=350, verbose_name='Организация'),
        ),
    ]
