# Generated by Django 4.0.2 on 2022-03-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0013_alter_project_p_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='s_img',
            field=models.FileField(upload_to='skills', verbose_name='Иконка svg 123x123px'),
        ),
    ]
