# Generated by Django 4.0.2 on 2022-04-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0014_alter_skills_s_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='b_link',
            field=models.CharField(max_length=250, verbose_name='Ссылка на Github'),
        ),
    ]
